require.NoError in fleet tests instead of continuing
When the fleet tests flake, they take out the rest of the test suite:

```
Step #24 - "submit-e2e-test-cloud-build": gke-autopilot-1.24: Step #2 - "e2e-stable": VERBOSE: --- FAIL: TestFleetScaleUpAllocateEditAndScaleDownToZero (163.39s)
Step #24 - "submit-e2e-test-cloud-build": gke-autopilot-1.24: Step #2 - "e2e-stable": VERBOSE: panic: runtime error: index out of range [0] with length 0 [recovered]
Step #24 - "submit-e2e-test-cloud-build": gke-autopilot-1.24: Step #2 - "e2e-stable": VERBOSE:     panic: runtime error: index out of range [0] with length 0
```

Looking at this file, it's easy to see why: if there's every an error
from any of these asserts, we just continue with the test and assume
the fleet is valid. But it's not.