Metadata missing, fails to start without it
error: error when retrieving current configuration of:
Resource: "allocation.agones.dev/v1, Resource=gameserverallocations", GroupVersionKind: "allocation.agones.dev/v1, Kind=GameServerAllocation"
Name: "", Namespace: "default"
from server for: "gameserverallocation.yaml": resource name may not be empty