Flaky: TestAllocatorAllocatePriority (#3280)
* Flaky: TestAllocatorAllocatePriority

Fix a flake that would see a feature flag flip _just_ between
`ApplyDefaults()` and `Validate()` -- which is more impressive than
anything else.

```
--- FAIL: TestAllocatorAllocatePriority (1.18s)
    allocator_test.go:169:
        	Error Trace:	/go/src/agones.dev/agones/pkg/gameserverallocations/allocator_test.go:169
        	            				/go/src/agones.dev/agones/pkg/gameserverallocations/allocator_test.go:176
        	Error:      	"[spec.selectors[0].counters: Forbidden: Feature CountsAndLists must be enabled spec.selectors[0].lists: Forbidden: Feature CountsAndLists must be enabled]" should have 0 item(s), but has 2
        	Test:       	TestAllocatorAllocatePriority
```

* Review updates.

* Found another small flake.